### PR TITLE
Fix show all routes; add limit for perf

### LINKED ISSUE #542: Show all routes on Feed Version Map is broken
## Observed behavior (please include a screenshot if possible)

Please explain what is being observed within the application here.

## Expected behavior

Clicking Show all Routes should display all route patterns

## Steps to reproduce the problem

Load feed version in Data Tools. Click 'Show all routes'.

image

## Any special notes on configuration used

N/A

## Version of datatools-ui and datatools-server if applicable (exact commit hash or branch name)

latest dev branches

### PR DESCRIPTION
**Pull request by landonreed**
### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JSDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

fix #542. Disable show all routes feature if shape record count is greater than one million.

### CODE REVIEW

File: lib/gtfs/components/ShowAllRoutesOnMapFilter.js [hunk 1]
```diff
@@ -1,30 +1,52 @@
...
   render () {
     const {
+      fetchStatus,
       showAllRoutesOnMap,
-      toggleShowAllRoutesOnMap
+      version
     } = this.props
-
+    // Disable if greater than one million records. We don't want to break
+    // Data Tools because of this shapes GraphQL fetch. This is a somewhat
```
Comment (binh-dam-ibigroup) [inline lib/gtfs/components/ShowAllRoutesOnMapFilter.js]: Why is this based on individual shapes instead on individual routes or route patterns that we plot somewhere else?

Comment (landonreed) [reply lib/gtfs/components/ShowAllRoutesOnMapFilter.js:34]: Because this is just showing the shapes on a map, where the other is showing patterns that are selectable in the editor. The editor piece isn't really working though. We should see if we can consolidate these though whenever we fix the editor piece.
