### PR TITLE
Fix GTFS editor lock

### LINKED ISSUE #175: Removing editor feed lock fails in Firefox when reloading page
<a href="https://github.com/landonreed"></img></a> **Issue by [landonreed](https://github.com/landonreed)**
_Wednesday Apr 04, 2018 at 20:10 GMT_
_Originally opened as https://github.com/catalogueglobal/datatools-ui/issues/69_

----

The editor feed lock is not released by the `beforeunload` event in Firefox on a simple page reload. It does appear to work when the tab is closed, but this is contrary to the behavior in Chrome which releases the lock both when the tab/window is closed AND when the page reloads.

### LINKED ISSUE #179: Attempts to access a locked editor feed results in inconsistent behavior
<a href="https://github.com/landonreed"></img></a> **Issue by [landonreed](https://github.com/landonreed)**
_Thursday Apr 26, 2018 at 17:07 GMT_
_Originally opened as https://github.com/catalogueglobal/datatools-ui/issues/73_

----

The new "locking" mechanism to prevent multiple users from editing a single feed in the editor is causing unexpected results. The `Must provide valid feedId parameter` error message is sometimes shown when attempting a re-lock.

### PR DESCRIPTION
**Pull request by binh-dam-ibigroup**
### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JSDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [na] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

Requires https://github.com/ibi-group/datatools-server/pull/477
Fix #175, Fix #179

This PR improves the editor locking feature as follows, in both Chrome and Firefox:
- Clicking "Re-lock feed" immediately enables the GTFS editor without the need to reload the page (one fewer click than before).
- Reloading an active editor tab/window no longer triggers the re-lock notice.
- The re-lock notice appears immediately after switching focus to a tab that doesn’t own the editor lock.

### CODE REVIEW

File: lib/editor/components/GtfsEditor.js [hunk 1]
```diff
@@ -126,6 +131,13 @@ type State = {
   activeTableId: ?string
 }
 
+/**
+ * Figures out the correct event name to use.
+ */
+function getNormalizedEvent (eventName: string) {
+  return window.attachEvent ? `on${eventName}` : eventName
```
Comment (philip-cline) [inline lib/editor/components/GtfsEditor.js:138]: This is for support of old IE versions?

**Review by philip-cline — APPROVED** [review]
All looking good to me, this is a very noticeable improvement thanks for making this fix!

File: lib/editor/components/GtfsEditor.js (hunk 1 above)
Comment (binh-dam-ibigroup) [reply lib/editor/components/GtfsEditor.js:138]: Joker card. I am not sure.

**Review by daniel-heppner-ibigroup — APPROVED** [review]
So great to finally have this fixed!
