### PR TITLE
fix(FeedVersionNavigator): ensure version index is set

### LINKED ISSUE #534: Issue Loading Feed Version Validation Page
## Observed behavior (please include a screenshot if possible)

Validation page in TDM does not load on the first click. It keeps showing retrieving validations. The browser needs to be refreshed in order to load the page.

## Expected behavior

Issues should load immediately when Validation tab is selected.

## Steps to reproduce the problem

It is currently unclear what exact conditions lead to this issue. It appears to only happen for certain feeds (e.g., see Muni screenshot). It may be related to the number of issues.

image

## Any special notes on configuration used

N/A

## Version of datatools-ui and datatools-server if applicable (exact commit hash or branch name)

N/A

### PR DESCRIPTION
**Pull request by landonreed**
### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JSDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

Fix #534. Note: the documented issue was most easy to reproduce by going to a feed source page, then navigating to the editor, then back to the feed source (home button) and finally viewing the validation issues.

### CODE REVIEW

File: lib/manager/components/version/FeedVersionNavigator.js [hunk 1]
```diff
@@ -61,9 +61,20 @@ export default class FeedVersionNavigator extends Component<Props, State> {
...
+    if (hasIndex) setVersionIndex(feedSource, feedVersionIndex, false)
+  }
+
   componentWillReceiveProps (nextProps: Props) {
-    if (nextProps.feedVersionIndex !== this.props.feedVersionIndex && nextProps.feedSource && nextProps.feedSource.feedVersions) {
-      this.props.setVersionIndex(nextProps.feedSource, nextProps.feedVersionIndex, false)
+    const {feedSource, feedVersionIndex} = nextProps
+    const indexChanged = feedVersionIndex !== this.props.feedVersionIndex
+    const hasVersions = feedSource && feedSource.feedVersions
+    if (indexChanged && hasVersions) {
```
Comment (binh-dam-ibigroup) [inline lib/manager/components/version/FeedVersionNavigator.js]: Also check that `typeof feedVersionIndex !== 'undefined'`?

File: lib/manager/actions/feeds.js [hunk 2]
```diff
@@ -183,8 +177,8 @@ export function onFeedSourceViewerMount (initialProps: any) {
       // Fetch feed source with versions and snapshots if not found.
       return dispatch(fetchFeedSource(feedSourceId, true))
     } else if (!feedSource.versions) {
+      // Fetch feed versions  (and related tables) if versions missing.
       dispatch(fetchRelatedTables(feedSource))
```
Comment (binh-dam-ibigroup) [inline lib/manager/actions/feeds.js]: Add `return` statement (or, document why there shouldn't be one)
