### PR TITLE
Navigate to latest feed version after processing complete

### LINKED ISSUE #643: UI should display merged feed version after merging (MTC)
## Observed behavior (please include a screenshot if possible)

After merging a feed version with another, datatools does not display the resulting merged feed version.

**Exception:** If the URL when performing a merge does not end in `/version/<n>`, then datatools does show the resulting version after merge.

## Expected behavior

Datatools should show the merged feed version after a merge.

## Steps to reproduce the problem

1. View a feed
2. Toggle between different versions.
3. Perform a merge
4. Datatools stays on the same on the feed version.

## Any special notes on configuration used

Configuration: MTC.

## Version of datatools-ui and datatools-server if applicable (exact commit hash or branch name)

Recent dev branch.

### PR DESCRIPTION
**Pull request by binh-dam-ibigroup**
### Checklist

- [X] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [X] Any modified or new methods or classes have helpful JSDoc and code is thoroughly commented
- [X] The description lists all applicable issues this PR seeks to resolve
- [na] The description lists any configuration setting(s) that differ from the default settings
- [ ] All tests and CI builds passing

### Description

This PR fixes #643.

Under the hood, the PR changes job handling so that if viewing a particular feed, datatools navigates to a new feed version when that version's processing is complete. Hopefully that does not create undesired side effects.

### CODE REVIEW

File: lib/manager/actions/status.js [hunk 1]
```diff
@@ -259,6 +260,17 @@ export function handleFinishedJob (job: ServerJob) {
...
+      case 'PROCESS_FEED':
+        // If viewing a particular feed, navigate to a new feed version as soon as it becomes available.
+        // It is the same path (without version number) as the link shown for this job status.
+        // (If user is not looking at this feed, don't navigate away from their current page.)
+        if (job.feedSourceId) {
+          const newVersionPath = `/feed/${job.feedSourceId}`
+          if (browserHistory.getCurrentLocation().pathname.startsWith(newVersionPath)) {
+            browserHistory.push(newVersionPath)
+          }
+        }
```
Comment (landonreed) [inline lib/manager/actions/status.js:272]: This generally looks good, a couple of comments:
- there is already logic in the `VALIDATE_FEED` case that fetches the feedSource. I think this check/browser push might be better if it were handled in a `then()` method following that fetch.
- there is a (tiny) bit of nuance missing in this check. If we're already on the feed source path, we don't really need to push to that path (the new version will load automatically). I think what we should be checking here is if someone is viewing a page that startsWith `/feed/${job.feedSourceId}/version`, then we push to `/feed/${job.feedSourceId}`.

**Review by landonreed — CHANGES_REQUESTED** [review]
Looks good! Just a couple of small tweaks.

File: lib/manager/actions/status.js (hunk 1 above)
Comment (binh-dam-ibigroup) [reply lib/manager/actions/status.js]: Updated in https://github.com/ibi-group/datatools-ui/pull/644/commits/ae230d68aa4b3b1b97d137f9ba63f5a036996e8f. You're right about the check, I intended to do that!

File: lib/manager/actions/feeds.js [hunk 2]
```diff
@@ -141,6 +141,14 @@ export function fetchFeedSource (feedSourceId: string) {
...
         return feedSource
       })
+      .then(() => {
+        // If viewing a particular feed, navigate to a new feed version as soon as it becomes available.
+        // (If user is not looking at this feed, don't navigate away from their current page.)
+        const newVersionPath = `/feed/${feedSourceId}`
+        if (browserHistory.getCurrentLocation().pathname.startsWith(`${newVersionPath}/version/`)) {
+          browserHistory.push(newVersionPath)
+        }
+      })
```
Comment (landonreed) [inline lib/manager/actions/feeds.js:151]: Oops, sorry for the confusion, I meant that this should go in the `then()` when `dispatch(fetchFeedSource())` is called in the switch statement in `actions/status.js`.

Comment (binh-dam-ibigroup) [reply lib/manager/actions/feeds.js]: Alright, updated in https://github.com/ibi-group/datatools-ui/pull/644/commits/e523505e7713ae582879443a8c57a0bafd70cf00.

**Review by landonreed — APPROVED** [review]

**Review by evansiroky — APPROVED** [review]
