### PR TITLE
Correctly show all modes in ServicePerModeChart

### LINKED ISSUE #610: ServicePerModeChart problem
## Observed behavior (please include a screenshot if possible)

If the first day in the ServicePerModeChart doesn't have all possible modes, the chart will look funky.

Screen Shot 2020-08-28 at 11 00 13 AM

## Expected behavior

Chart renders all possible modes for all possible days.

## Steps to reproduce the problem

Load [this feed](http://transitfeeds.com/p/kitsap-transit/296/latest).

## Any special notes on configuration used

n/a

## Version of datatools-ui and datatools-server if applicable (exact commit hash or branch name)

https://github.com/conveyal/datatools-ui/commit/646dfcf9fca26ff9fbb4e6c5c129036f94ce57d3

### PR DESCRIPTION
**Pull request by evansiroky**
### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JSDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

fixes #610

### CODE REVIEW

File: lib/manager/components/validation/ServicePerModeChart.js [hunk 1]
```diff
@@ -15,46 +14,47 @@ type Props = {
...
+      column.other = column.total -
+        column.bus -
+        column.metro -
+        column.rail -
+        column.tram
+      orderedPossibleModes.forEach(mode => {
+        if (column[mode] > 0) {
+          modes[mode] = true
+        }
+      })
```
Comment (landonreed) [inline lib/manager/components/validation/ServicePerModeChart.js:54]: Why not just do this check for modes with value > 0 in the filter below after the `this._getData` call? The way it currently is feels a little obfuscated. Alternatively, if you decide to keep it this way, the `modes` key could use a more descriptive name e.g., `modesWithData` or something.

File: lib/manager/components/validation/ServicePerModeChart.js [hunk 2]
```diff
@@ -15,46 +14,47 @@ type Props = {
 }
 
 const maxDaysToShow = 500
+const orderedPossibleModes = ['other', 'metro', 'rail', 'tram', 'bus']
```
Comment (landonreed) [inline lib/manager/components/validation/ServicePerModeChart.js:17]: Non-blocking style comment: a more clear name to me would just be `ALL_MODES`.

File: lib/manager/components/validation/ServicePerModeChart.js (hunk 1 above)
Comment (evansiroky) [reply lib/manager/components/validation/ServicePerModeChart.js]: I ended up doing the check in the filter as you recommended.

**Review by binh-dam-ibigroup — APPROVED** [review]
