### PR TITLE
Refactor Deployment fields to fix perf issues

### LINKED ISSUE #574: Performance issues on fetch all OTP deployments
When fetching the 511NY list of deployments with the latest dev branch of datatools-server. The response can take up to (!!!!!) one minute. After some debugging, this looks to be attributed to AWS calls for ec2 instances assigned to each deployment/server. These calls are happening for the JSON properties `#project` as well as `#ec2Instances`.

### PR DESCRIPTION
**Pull request by landonreed**
### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JSDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

This corresponds to changes in ibi-group/datatools-server#310, which removes a couple of JsonProperty annotated fields from the getAllDeployments response.

fix #574

### CODE REVIEW

File: lib/manager/components/CurrentDeploymentPanel.js [hunk 1]
```diff
@@ -35,6 +43,12 @@ export default class CurrentDeploymentPanel extends Component<Props, State> {
     activeSummaryIndex: 0
   }
 
+  componentDidMount () {
+    // Fetch single deployment. This JSON response will contain the #ec2Instances
+    // field, which does not come with this field (to prevent a very slow response).
```
Comment (binh-dam-ibigroup) [inline lib/manager/components/CurrentDeploymentPanel.js:48]: Do you mean 'which is not available from `this.props.deployment`'?

Comment (binh-dam-ibigroup) [reply lib/manager/components/CurrentDeploymentPanel.js:48]: (Keep '... to prevent a slow response' of course.)
