### PR TITLE
Fix pattern name editor bug

### LINKED ISSUE #556: GTFS Editor: Pattern Name Edit Reverts User Changes Due to Editor Lock Request
While editing a trip pattern name in the GTFS Editor, if the EditableTextField is in an edit state while the editor makes a lock request (the editor occasionally makes these to keep a session lock on the feed being edited to prevent multiple editing sessions), the changes to the pattern name will be reverted back to the previous value.

To recreate:
1. Open a feed in the editor.
2. Select a route, and create a new pattern.
3. Click edit name, quickly change the value (without saving) and then wait a few seconds.

### PR DESCRIPTION
**Pull request by landonreed**
### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JSDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

fix #556 by not resetting EditableTextField value if editing session is in progress.

### CODE REVIEW

File: lib/common/components/EditableTextField.js [hunk 1]
```diff
@@ -47,12 +47,20 @@ export default class EditableTextField extends Component<Props, State> {
   }
 
   componentWillReceiveProps (nextProps: Props) {
-    if (this.state.value !== nextProps.value) {
-      // Update value if externally changed.
+    const {initialValue, isEditing, value} = this.state
```
Comment (binh-dam-ibigroup) [inline lib/common/components/EditableTextField.js:50]: Also extract nextProps.value into its own variable.
