### PR TITLE
fix(EntityListButton): Fix `New Exception` button formatting

### LINKED ISSUE #725: New exception button pushed to new line
## Observed behavior (please include a screenshot if possible)

The `New Exception` button is pushed awkwardly to a new line in the UI, which makes it difficult to click the `Edit Schedules` button. 
image

## Expected behavior

The `New Exception` button should be rendered in line with the toolbar. 

## Steps to reproduce the problem

1. Head to https://gtfs.ibi-transit.com/
2. Open the editor for any feed
3. Open Calendar menu
4. Click exceptions tab
5. Verify that the new exception button does not render properly. 

## Any special notes on configuration used

NA

## Version of datatools-ui and datatools-server if applicable (exact commit hash or branch name)

image

### PR DESCRIPTION
**Pull request by philip-cline**
Avoid `New Exception` button being moved to new lines based on size. Fixes #725.

fix #725

### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JSDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

Changed the New Exception button maxWidth property to avoid the button being moved to a new line, as in issue #725.

### CODE REVIEW

File: lib/editor/components/EntityListButtons.js [hunk 1]
```diff
@@ -169,7 +169,9 @@ export default class EntityListButtons extends Component<Props, State> {
             bsSize='small'
             data-test-id={`new-${activeComponent}-button`}
             disabled={entities && entities.findIndex(entityIsNew) !== -1}
-            onClick={this._onClickNew}>
+            onClick={this._onClickNew}
+            // Setting the max width to display value so the button does not move to new line
```
Comment (binh-dam-ibigroup) [inline lib/editor/components/EntityListButtons.js:173]: Add "based on the width of the 'New calendar' button".

Comment (binh-dam-ibigroup) [reply lib/editor/components/EntityListButtons.js:173]: Add also a note that the width of the button text varies depending on the font used.

**Review by binh-dam-ibigroup — APPROVED** [review]
Just two adjustments to the comments, but it should be good to go.
