### PR TITLE
fix: correct coordIsOutOfBounds behavior

### LINKED ISSUE #825: Error creating pattern shapes using 'From stops'
## Observed behavior (please include a screenshot if possible)

Upon creating a route shape pattern by clicking the option of 'From Stops', the following error is generated.

image

## Expected behavior

It should snap to streets and create a proper shape pattern as it was previously doing. It worked perfectly a few weeks back.

## Steps to reproduce the problem

1. Create any route
2. Create the trip pattern by adding the stops in order of the journey.
3. Click 'From stops' button to generate shape.
image
4. Click 'OK' button to confirm creating the shape.
image
5. The Error is displayed.

## Any special notes on configuration used

None.

## Version of datatools-ui and datatools-server if applicable (exact commit hash or branch name)

image

### PR DESCRIPTION
**Pull request by miles-grant-ibigroup**
### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JSDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

#808 contained a bug that prevented it from working properly. As a result, a valid configuration would sometimes route graphhopper requests to the wrong server. This PR fixes this bug.

I've done some testing and it looks like this closes #825, but I would appreciate some verification of this

### CODE REVIEW

**Review by philip-cline — APPROVED** [review]
Thanks for fixing this & adding a test. Working well for me and looks it fixes #825

File: lib/common/util/__tests__/map.js [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+
+    it('should correctly determine if a coordinate is outside set bounds', () => {
+      expect(coordIsOutOfBounds(SOMEWHERE_IN_CANADA, APPROX_NORTH_AMERICA_BOUNDS)).toEqual(false)
+      expect(coordIsOutOfBounds(NULL_ISLAND, APPROX_NORTH_AMERICA_BOUNDS)).toEqual(true)
+    })
+    it('should correctly determine handle strange bounds', () => {
+      expect(coordIsOutOfBounds(SOMEWHERE_IN_CANADA, NULL_BOUNDS)).toEqual(true)
+      expect(coordIsOutOfBounds(NULL_ISLAND, NULL_BOUNDS)).toEqual(true)
+    })
+    it('should correctly handle either argument being null', () => {
```
Comment (binh-dam-ibigroup) [inline lib/common/util/__tests__/map.js]:
```suggestion
    it('should correctly handle null/undefined arguments', () => {
```

**Review by binh-dam-ibigroup — APPROVED** [review]
