### PR TITLE
fix(gtfs-search): Display GTFS routes in search results.

### LINKED ISSUE #932: Routes are not shown when searching one from alert editor
## Observed behavior (please include a screenshot if possible)

When creating a new service alert at http://localhost:9966/alerts/new, when searching for a route in the "Add stop/route" dropdown, only stops are suggested.

## Expected behavior

Transit routes should appear according to typed filter too.

## Steps to reproduce the problem

1. Create a new alert.
2. Type some id in the "Add stop/route" field
3. Observe that only stops are shown, and no routes are suggested.

## Any special notes on configuration used

NA

## Version of datatools-ui and datatools-server if applicable (exact commit hash or branch name)

Current version of datatools UI.

### PR DESCRIPTION
**Pull request by binh-dam-ibigroup**
### Checklist

- [x] Appropriate branch selected => This PR is for MTC. A similar PR to dev will be made upon their approval
- [x] Any modified or new methods or classes have helpful JSDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [na] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

Fix #932.

### CODE REVIEW

**Review by philip-cline — APPROVED** [review]
Works well for me

File: lib/gtfs/components/gtfs-search.js [hunk 1]
```diff
@@ -153,11 +153,14 @@ class GtfsSearch extends Component<Props, State> {
...
             routes && routeOptions.push(
               ...routes
-                // Remove specified entity ids (route ids in this case) to exclude, except the current value.
-                .filter(route =>
-                  !excludedEntityIds.includes(route.route_id) ||
-                  // (Extended type checks are for flow validation.)
-                  (route.route_id === (typeof currentOption === 'object' ? currentOption && currentOption.value : currentOption))
+                // Keep routes whose ids are not excluded and that are not the one selected in the dropdown.
+                .filter(route => {
+                  const isExcluded = excludedEntityIds && excludedEntityIds.includes(route.route_id)
```
Comment (miles-grant-ibigroup) [inline lib/gtfs/components/gtfs-search.js]: Should we extract `route.route_id` and do a null check?

**Review by miles-grant-ibigroup — APPROVED** [review]
Very clean! Thanks for implementing this
