### PR TITLE
fix(LabelEditor): show admin-only checkbox to project admins

### LINKED ISSUE #705: Label editor does not show admin checkbox for project admins
## Observed behavior (please include a screenshot if possible)

When the label editor modal is open, the admin checkbox is not visible for project admins:
image

## Expected behavior

Project admins and application admins should see this checkbox. This check is too restrictive:
https://github.com/ibi-group/datatools-ui/blob/dev/lib/manager/components/LabelEditor.js#L75

Anywhere else the organization admin is used should be replaced with project admin.

## Steps to reproduce the problem

1. Log in as project admin
2. Edit existing or create new label
3. Observe missing checkbox per screenshot

## Any special notes on configuration used

N/A

## Version of datatools-ui and datatools-server if applicable (exact commit hash or branch name)

latest dev

### PR DESCRIPTION
**Pull request by miles-grant-ibigroup**
### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JSDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing
### Description

Closes #705. Permissions for the admin-only checkbox were being determined incorrectly. Fixed by having it match the method used to show the edit/delete buttons, which is also the method used by the server.

### CODE REVIEW

**Review by landonreed — APPROVED** [review]
LGTM! Thanks for verifying that the server permissions check is set up correctly!

File: lib/manager/components/LabelEditorModal.js [hunk 1]
```diff
@@ -60,7 +60,7 @@ export default class LabelEditorModal extends React.Component<
           <LabelEditor
             label={label}
             onDone={this.close}
-            projectId={projectId}
+            projectId={projectId || label.projectId}
```
Comment (binh-dam-ibigroup) [inline lib/manager/components/LabelEditorModal.js:63]: What is the issue with `projectId` here?

**Review by binh-dam-ibigroup — APPROVED** [review]
LGTM, perhaps insert a comment regarding providing a default project id for the `LabelEditor`.

File: lib/manager/components/LabelEditorModal.js (hunk 1 above)
Comment (miles-grant-ibigroup) [reply lib/manager/components/LabelEditorModal.js:66]: Good call on adding some comments thanks! This was the cleanest way I could come up with to support both editing and creating a label. Clarification added in 472950e2

**Comment by miles-grant-ibigroup** [comment]
Thanks all for reviewing! Assigning back to @landonreed to merge.
